[build]
  command = "prisma generate && next build"
  publish = ".next"

[build.environment]
  DISABLE_NETLIFY_DRAWER = "true"

[context.production.environment]
  DISABLE_NETLIFY_DRAWER = "true"

[context.deploy-preview.environment]
  DISABLE_NETLIFY_DRAWER = "true"

[context.branch-deploy.environment]
  DISABLE_NETLIFY_DRAWER = "true"
